### PR TITLE
Add cypress

### PR DESCRIPTION
**Pull request by Ernestopheles**
Cypress scripts to offer some very basic online tests for isotope-demo frontend and backend.

Get Cypress installed, read the basic docs and enjoy!

### CODE REVIEW

**Comment by Ernestopheles** [comment]
I did not run these scripts against the latest version of isotope-demo (new theme) yet.

**Comment by Ernestopheles** [comment]
Tested with latest isotope-demo version

**Comment by aschempp** [comment]
Sorry but I don't think this makes sense here. Adding it to this GitHub Repository would mean everyone installing the Isotope Demo would get these scripts locally. Is this supposed to test the "design" or "content" of the Isotope demo, or the functionality of Contao/Isotope?

**Comment by Ernestopheles** [comment]
It's designed to regression test the functionality of Isotope BE and FE

**Comment by Ernestopheles** [comment]
A running website is necessary to run Cypress tests. Best maybe to use the Demo to get reproduceable and consistent tests.

Installation of Cypress can be everywhere (usually outside of the Demo project folder). Add a folder and get Cypress installed in there. Add the given scripts and config files.

**Comment by aschempp** [comment]
yes it makes sense to use the demo for the tests. But the tests do not test the demo, they test Isotope. So they should not be in this repository. Maybe you can create a separate repository that can be used with Isotope AND the demo to run the tests?

**Comment by Ernestopheles** [comment]
So there are 2 options now

1. Integrate the Cypress tests to Isotope core

2. Build a separate test repository for Isotope tests

Contao core uses option 1...

**Pull request closed without merging**
